# Generated by Django 5.2.15 on 2026-06-09 08:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0043_auto_20260518_1206'),
        ('part', '0150_part_maximum_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametricBomItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_formula', models.CharField(blank=True, default='', help_text='Formula for dynamic quantity. Example: CEIL(param.长度 / 500) * 2', max_length=512, verbose_name='Quantity formula')),
                ('condition_formula', models.CharField(blank=True, default='', help_text='Boolean formula that determines if this item is included. Empty = always included. Example: param.速度 > 15', max_length=512, verbose_name='Condition formula')),
                ('part_selector_formula', models.CharField(blank=True, default='', help_text='Formula to dynamically select which sub-part to use. Example: IF(param.speed>15, "MOTOR-A", "MOTOR-B")', max_length=512, verbose_name='Part selector formula')),
                ('formular_hash', models.CharField(blank=True, default='', editable=False, help_text='SHA-256 hash of all three formulas for change detection', max_length=64, verbose_name='Formula hash')),
                ('bom_item', models.OneToOneField(help_text='The BOM item this parametric configuration extends', on_delete=django.db.models.deletion.CASCADE, related_name='parametric_config', to='part.bomitem', verbose_name='BOM item')),
            ],
            options={
                'verbose_name': 'Parametric BOM item',
                'verbose_name_plural': 'Parametric BOM items',
            },
        ),
        migrations.CreateModel(
            name='ParametricRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('constraint', 'Constraint'), ('calculation', 'Calculation'), ('visibility', 'Visibility')], default='constraint', max_length=32, verbose_name='Rule type')),
                ('condition_formula', models.CharField(blank=True, default='', help_text='Formula that triggers this rule. Leave empty for always-active rules. Example: param.长度 > 8000', max_length=512, verbose_name='Condition formula')),
                ('action', models.CharField(choices=[('set_value', 'Set value'), ('set_min', 'Set minimum'), ('set_max', 'Set maximum'), ('show', 'Show'), ('hide', 'Hide'), ('require', 'Require')], default='set_value', help_text='What action to perform when the condition is met', max_length=32, verbose_name='Action')),
                ('value_formula', models.CharField(blank=True, default='', help_text='Formula computing the value for set_value / set_min / set_max actions', max_length=512, verbose_name='Value formula')),
                ('error_message', models.CharField(blank=True, default='', help_text='User-facing message when a constraint rule is violated', max_length=256, verbose_name='Error message')),
                ('priority', models.IntegerField(default=100, help_text='Rule evaluation priority (lower = evaluated first)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Priority')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('product_part', models.ForeignKey(help_text='The parametric product template this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='parametric_rules', to='part.part', verbose_name='Product part')),
                ('target_param', models.ForeignKey(blank=True, help_text='Parameter this rule affects', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametric_rules', to='common.parametertemplate', verbose_name='Target parameter')),
            ],
            options={
                'verbose_name': 'Parametric rule',
                'verbose_name_plural': 'Parametric rules',
                'ordering': ['product_part', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='ProductConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Human-friendly name for this configuration', max_length=128, verbose_name='Title')),
                ('revision', models.CharField(blank=True, default='1.0', max_length=32, verbose_name='Revision')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('released', 'Released'), ('obsolete', 'Obsolete')], default='draft', max_length=32, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('params_snapshot', models.JSONField(blank=True, help_text='Full parameter name-value map at configuration time', null=True, verbose_name='Parameter snapshot')),
                ('generated_bom', models.JSONField(blank=True, help_text='Generated BOM snapshot after parameter evaluation', null=True, verbose_name='Generated BOM')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Total cost')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametric_configurations', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('template_part', models.ForeignKey(help_text='The parametric product template used for this configuration', on_delete=django.db.models.deletion.CASCADE, related_name='product_configurations', to='part.part', verbose_name='Template part')),
            ],
            options={
                'verbose_name': 'Product configuration',
                'verbose_name_plural': 'Product configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartParameterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.CharField(blank=True, default='', help_text='Default value when the parameter is not explicitly set', max_length=128, verbose_name='Default value')),
                ('min_value', models.FloatField(blank=True, help_text='Minimum allowed value (numeric parameters only)', null=True, verbose_name='Minimum value')),
                ('max_value', models.FloatField(blank=True, help_text='Maximum allowed value (numeric parameters only)', null=True, verbose_name='Maximum value')),
                ('options', models.JSONField(blank=True, help_text='List of valid options for dropdown/select parameters', null=True, verbose_name='Options')),
                ('is_driving', models.BooleanField(default=True, help_text='User/customer provides this value during configuration', verbose_name='Driving parameter')),
                ('is_computed', models.BooleanField(default=False, help_text='Calculated automatically by a formula', verbose_name='Computed parameter')),
                ('computation_formula', models.CharField(blank=True, default='', help_text='Formula for computing this parameter value. Example: param.载重 * param.速度 / 0.85', max_length=512, verbose_name='Computation formula')),
                ('ui_hint', models.CharField(blank=True, default='', help_text='Hint text shown to the user during configuration', max_length=256, verbose_name='UI hint')),
                ('display_order', models.IntegerField(default=0, help_text='Order in the configuration UI (lower = earlier)', verbose_name='Display order')),
                ('visible_on_config', models.BooleanField(default=True, help_text='Show this parameter on the product configurator page', verbose_name='Visible on configurator')),
                ('part', models.ForeignKey(help_text='The part this parameter configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='parametric_configs', to='part.part', verbose_name='Part')),
                ('template', models.ForeignKey(help_text='The parameter template this config is based on', on_delete=django.db.models.deletion.CASCADE, related_name='parametric_configs', to='common.parametertemplate', verbose_name='Parameter template')),
            ],
            options={
                'verbose_name': 'Part parameter config',
                'verbose_name_plural': 'Part parameter configs',
                'ordering': ['display_order', 'template'],
                'unique_together': {('part', 'template')},
            },
        ),
        migrations.CreateModel(
            name='ConfigParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, default='', max_length=128, verbose_name='Value')),
                ('source', models.CharField(choices=[('manual', 'Manual input'), ('computed', 'Computed by formula'), ('inherited', 'Inherited from parent'), ('default', 'Default value')], default='manual', help_text='How this value was determined', max_length=32, verbose_name='Source')),
                ('computed_at', models.DateTimeField(blank=True, null=True, verbose_name='Computed at')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.parametertemplate', verbose_name='Parameter template')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_values', to='parametric_bom.productconfiguration', verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Configuration parameter value',
                'verbose_name_plural': 'Configuration parameter values',
                'unique_together': {('config', 'template')},
            },
        ),
    ]
