# Generated by Django 5.2.15 on 2026-06-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partparameterconfig',
            name='parameter_type',
            field=models.CharField(choices=[('number', '数值'), ('option', '选项'), ('multi_option', '多选项'), ('boolean', '布尔'), ('text', '文本'), ('long_text', '长文本'), ('file_ref', '文件引用'), ('part_ref', '零件引用')], default='number', help_text='Data type of this parameter', max_length=20, verbose_name='Parameter type'),
        ),
    ]
