# Generated by Django 5.2.15 on 2026-06-09 10:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_auto_20260518_1206'),
        ('company', '0080_company_tags'),
        ('parametric_bom', '0002_partparameterconfig_parameter_type'),
        ('part', '0150_part_maximum_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametricbomitem',
            name='mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('qty_formula', 'Qty formula'), ('conditional', 'Conditional include'), ('candidate', 'Select from candidates'), ('variant', 'Generate variant from template'), ('specification', 'Outsource by specification'), ('supplier', 'Select supplier'), ('structure', 'Structure control')], default='qty_formula', help_text='How this BOM item resolves its sub-part', max_length=32, verbose_name='Part mode'),
        ),
        migrations.CreateModel(
            name='BomCandidatePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text='Short descriptive label shown in the UI (e.g. "小电机")', max_length=128, verbose_name='Label')),
                ('condition_formula', models.CharField(blank=True, default='', help_text='Formula that determines if this candidate is selected. Leave empty for always-available. Example: param.载重 <= 1000', max_length=512, verbose_name='Condition formula')),
                ('priority', models.IntegerField(default=100, help_text='Lower values are checked first (0 = highest priority)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Priority')),
                ('parametric_bom_item', models.ForeignKey(help_text='The parametric BOM item this candidate belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_parts', to='parametric_bom.parametricbomitem', verbose_name='Parametric BOM item')),
                ('part', models.ForeignKey(help_text='The part to use when this candidate is selected', on_delete=django.db.models.deletion.CASCADE, related_name='bom_candidates', to='part.part', verbose_name='Candidate part')),
            ],
            options={
                'verbose_name': 'Candidate part',
                'verbose_name_plural': 'Candidate parts',
                'ordering': ['parametric_bom_item', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='BomSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_type', models.CharField(default='custom', help_text='Type of specification (e.g. "outsource", "raw_material", "custom")', max_length=64, verbose_name='Specification type')),
                ('spec_fields', models.JSONField(blank=True, default=list, help_text='List of {name, formula, unit} dicts defining the specs. Example: [{"name": "材质", "formula": "\'Q235\'"}, {"name": "长度", "formula": "parent.货架高度+100", "unit": "mm"}]', verbose_name='Specification fields')),
                ('drawing_ref_formula', models.CharField(blank=True, default='', help_text="Formula for auto-generating the drawing number. Example: 'DWG-' + param.订单号", max_length=256, verbose_name='Drawing reference formula')),
                ('unit_cost_formula', models.CharField(blank=True, default='', help_text='Formula estimating the unit cost. Example: param.长度 * 0.035 + 25', max_length=256, verbose_name='Unit cost formula')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional processing notes for the workshop', verbose_name='Notes')),
                ('parametric_bom_item', models.OneToOneField(help_text='The parametric BOM item this specification describes', on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='parametric_bom.parametricbomitem', verbose_name='Parametric BOM item')),
            ],
            options={
                'verbose_name': 'BOM specification',
                'verbose_name_plural': 'BOM specifications',
            },
        ),
        migrations.CreateModel(
            name='SupplierSelectionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_formula', models.CharField(blank=True, default='', help_text='Formula that triggers this supplier selection. Empty = always use. Example: param.数量 > 1000', max_length=512, verbose_name='Condition formula')),
                ('priority', models.IntegerField(default=100, help_text='Lower values are checked first (0 = highest priority)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Priority')),
                ('label', models.CharField(blank=True, default='', help_text='Short label shown in UI (e.g. "批量价", "零售价")', max_length=128, verbose_name='Label')),
                ('parametric_bom_item', models.ForeignKey(help_text='The parametric BOM item this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_rules', to='parametric_bom.parametricbomitem', verbose_name='Parametric BOM item')),
                ('supplier_part', models.ForeignKey(help_text='The supplier part to use when this rule matches', on_delete=django.db.models.deletion.CASCADE, related_name='parametric_rules', to='company.supplierpart', verbose_name='Supplier part')),
            ],
            options={
                'verbose_name': 'Supplier selection rule',
                'verbose_name_plural': 'Supplier selection rules',
                'ordering': ['parametric_bom_item', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='VariantMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_mapping', models.JSONField(blank=True, default=dict, help_text='JSON dict mapping template parameter names → formulas. Example: {"高度": "parent.货架高度", "材质": "\'Q235\'"}', verbose_name='Parameter mapping')),
                ('variant_name_template', models.CharField(blank=True, default='', help_text='Template for the generated variant name. Use {param_name} syntax. Example: "立柱-H{高度}" → "立柱-H2800"', max_length=256, verbose_name='Variant name template')),
                ('auto_generate', models.BooleanField(default=True, help_text='Automatically create the variant part when the configuration is completed. Disable for manual generation only.', verbose_name='Auto-generate')),
                ('parametric_bom_item', models.OneToOneField(help_text='The parametric BOM item this variant mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='variant_mapping', to='parametric_bom.parametricbomitem', verbose_name='Parametric BOM item')),
                ('template_part', models.ForeignKey(help_text='The parametric template part to generate variants from. This part should have is_template=True.', on_delete=django.db.models.deletion.CASCADE, related_name='variant_mappings', to='part.part', verbose_name='Template part')),
            ],
            options={
                'verbose_name': 'Variant mapping',
                'verbose_name_plural': 'Variant mappings',
            },
        ),
        migrations.CreateModel(
            name='InheritanceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(blank=True, default='', help_text='Optional transformation formula. Use parent.xxx for parent params, param.xxx for own params. Default: parent.source_template.name', max_length=256, verbose_name='Formula')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('source_template', models.ForeignKey(blank=True, help_text='The source parameter on the parent. Leave empty to use parent. source_template.name', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inheritance_sources', to='common.parametertemplate', verbose_name='Source parameter')),
                ('target_part', models.ForeignKey(help_text='The child part that receives the inherited parameter', on_delete=django.db.models.deletion.CASCADE, related_name='inheritance_mappings', to='part.part', verbose_name='Target part')),
                ('target_template', models.ForeignKey(help_text='The parameter on the target part to receive the value', on_delete=django.db.models.deletion.CASCADE, related_name='inheritance_targets', to='common.parametertemplate', verbose_name='Target parameter')),
            ],
            options={
                'verbose_name': 'Inheritance mapping',
                'verbose_name_plural': 'Inheritance mappings',
                'unique_together': {('target_part', 'target_template')},
            },
        ),
        migrations.CreateModel(
            name='PartAttributeFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(help_text='Name of the attribute (e.g. "weight", "color_code", "inspection_standard")', max_length=64, verbose_name='Attribute name')),
                ('attribute_type', models.CharField(choices=[('number', '数值'), ('option', '选项'), ('multi_option', '多选项'), ('boolean', '布尔'), ('text', '文本'), ('long_text', '长文本'), ('file_ref', '文件引用'), ('part_ref', '零件引用')], default='text', help_text='Data type of this attribute value', max_length=20, verbose_name='Attribute type')),
                ('formula', models.CharField(help_text='Formula that computes this attribute. Example: param.长度 * param.宽度 * 5 * 7.85 / 1000000', max_length=512, verbose_name='Formula')),
                ('unit', models.CharField(blank=True, default='', help_text='Unit of measurement (e.g. "kg", "mm", "pcs")', max_length=32, verbose_name='Unit')),
                ('display_order', models.IntegerField(default=0, help_text='Order in the attribute list (lower = earlier)', verbose_name='Display order')),
                ('part', models.ForeignKey(help_text='The part this attribute formula belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attribute_formulas', to='part.part', verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Part attribute formula',
                'verbose_name_plural': 'Part attribute formulas',
                'ordering': ['part', 'display_order'],
                'unique_together': {('part', 'attribute_name')},
            },
        ),
    ]
