# Generated by Django 5.2.15 on 2026-06-09 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0043_auto_20260518_1206'),
        ('parametric_bom', '0003_parametricbomitem_mode_bomcandidatepart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partparameterconfig',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Display name of this parameter (used when no template is set)', max_length=128, verbose_name='Parameter name'),
        ),
        migrations.AlterField(
            model_name='partparameterconfig',
            name='template',
            field=models.ForeignKey(blank=True, help_text='The parameter template this config is based on (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametric_configs', to='common.parametertemplate', verbose_name='Parameter template'),
        ),
    ]
