# Generated by Django 5.2.15 on 2026-06-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0004_make_template_optional_add_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partparameterconfig',
            name='step_value',
            field=models.FloatField(blank=True, default=1.0, help_text='Step/increment value for numeric slider and inputs', null=True, verbose_name='Step value'),
        ),
    ]
