# Generated by Django 5.2.15 on 2026-06-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0006_remove_mode_add_enable_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametricbomitem',
            name='reference_formula',
            field=models.CharField(blank=True, default='', help_text='Formula for dynamic reference/notes. Example: CONCAT("定制-", param.长度, "mm")', max_length=512, verbose_name='Reference formula'),
        ),
        migrations.AddField(
            model_name='parametricbomitem',
            name='supplier_formula',
            field=models.CharField(blank=True, default='', help_text='Formula to dynamically select supplier. Example: IF(param.速度>30, "德国SEW", "国茂")', max_length=512, verbose_name='Supplier formula'),
        ),
    ]
