# Generated by Django 5.2.15 on 2026-06-23 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0007_parametricbomitem_reference_formula_and_more'),
        ('part', '0150_part_maximum_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name used in formulas (e.g. "总重量", "板面积")', max_length=64, verbose_name='Variable name')),
                ('formula', models.CharField(help_text='Expression that computes this variable. Can reference other variables and param.* values.', max_length=1024, verbose_name='Formula / expression')),
                ('description', models.CharField(blank=True, default='', help_text='Optional description of what this variable represents', max_length=256, verbose_name='Description')),
                ('display_order', models.IntegerField(default=0, help_text='Order in the variables list (lower = earlier)', verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametric_variables', to='part.part', verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Part variable',
                'verbose_name_plural': 'Part variables',
                'ordering': ['part', 'display_order'],
                'unique_together': {('part', 'name')},
            },
        ),
    ]
