# Generated by Django 5.2.15 on 2026-06-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0008_partvariable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametricbomitem',
            name='enable_supplier',
        ),
        migrations.RemoveField(
            model_name='parametricbomitem',
            name='supplier_formula',
        ),
        migrations.AddField(
            model_name='variantmapping',
            name='variant_ipn_template',
            field=models.CharField(blank=True, default='', help_text='Template for the generated variant IPN/part number. Use {param_name} syntax. Example: "COL-{高度}-{宽度}" → "COL-2800-1500"', max_length=256, verbose_name='Variant IPN template'),
        ),
        migrations.DeleteModel(
            name='SupplierSelectionRule',
        ),
    ]
