# Generated by Django 5.2.15 on 2026-07-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0009_variant_ipn_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametricbomitem',
            name='param_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='JSON dict mapping child parameter names → formulas. Available for both static and dynamic items. Example: {"载重": "parent.载重", "速度": "parent.速度*1.2"}', verbose_name='Parameter mapping'),
        ),
    ]
