# Generated by Django 5.2.15 on 2026-07-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0010_parametricbomitem_param_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantmapping',
            name='auto_generate',
        ),
    ]
