# Generated by Django 5.2.15 on 2026-07-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0011_remove_variantmapping_auto_generate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametricbomitem',
            name='part_selector_formula',
        ),
    ]
