# Generated by Django 5.2.15 on 2026-07-02 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0012_remove_part_selector_formula'),
        ('part', '0150_part_maximum_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', help_text='Session identifier for anonymous users', max_length=64, verbose_name='Session key')),
                ('item_type', models.CharField(choices=[('parametric', 'Parametric product'), ('static', 'Static part')], default='parametric', max_length=20, verbose_name='Item type')),
                ('parameters', models.JSONField(blank=True, help_text='Parameter name-value map at add-to-cart time', null=True, verbose_name='Parameter snapshot')),
                ('bom_snapshot', models.JSONField(blank=True, help_text='BOM expansion result cached at add-to-cart time', null=True, verbose_name='BOM snapshot')),
                ('title', models.CharField(blank=True, default='', help_text='Human-friendly name for this cart item', max_length=256, verbose_name='Title')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(blank=True, help_text='The static part (for static items)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items_as_part', to='part.part', verbose_name='Part')),
                ('product_part', models.ForeignKey(blank=True, help_text='The parametric product template (for parametric items)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items_as_product', to='part.part', verbose_name='Product part')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cart item',
                'verbose_name_plural': 'Cart items',
                'ordering': ['-created_at'],
            },
        ),
    ]
