# Generated by Django 5.2.15 on 2026-07-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0013_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Unit price at add-to-cart time', max_digits=19, null=True, verbose_name='Unit price'),
        ),
    ]
