# Generated by Django 5.2.15 on 2026-07-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0014_cartitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametricbomitem',
            name='price_formula',
            field=models.CharField(blank=True, default='', help_text='Formula for dynamic unit price. Use 子件单价 for the sub-part base price. Example: 子件单价 * CEIL(param.长度 / 1000)', max_length=512, verbose_name='Price formula'),
        ),
    ]
