# Generated by Django 5.2.15 on 2026-07-07 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0080_company_tags'),
        ('parametric_bom', '0015_parametricbomitem_price_formula'),
        ('part', '0150_part_maximum_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Project name')),
                ('project_code', models.CharField(blank=True, default='', help_text='Auto-generated project code (PRJ-YYYYMMDD-XXXX)', max_length=64, unique=True, verbose_name='Project code')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('purchasing', 'Purchasing'), ('production', 'Production'), ('delivery', 'Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=32, verbose_name='Status')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('is_public', models.BooleanField(default=False, help_text='Non-members can view this project', verbose_name='Public')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag: set to False to hide/archive', verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametric_projects', to='company.company', verbose_name='Customer')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('members', models.ManyToManyField(blank=True, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Members')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('configuration', 'Product configuration'), ('part', 'Static part')], default='configuration', max_length=20, verbose_name='Item type')),
                ('title', models.CharField(blank=True, default='', max_length=256, verbose_name='Title')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('bom_snapshot', models.JSONField(blank=True, help_text='Expanded BOM result cached at add-to-project time', null=True, verbose_name='BOM snapshot')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Unit cost')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Unit price')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_items', to='part.part', verbose_name='Part')),
                ('product_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_items', to='parametric_bom.productconfiguration', verbose_name='Product configuration')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='parametric_bom.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project item',
                'verbose_name_plural': 'Project items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
