# Generated by Django 5.2.15 on 2026-07-07 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0016_project_projectitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_template',
            field=models.BooleanField(default=False, help_text='This project can be used as a template', verbose_name='Is template'),
        ),
        migrations.AddField(
            model_name='project',
            name='template_source',
            field=models.ForeignKey(blank=True, help_text='The template this project was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_copies', to='parametric_bom.project', verbose_name='Template source'),
        ),
    ]
