# Generated by Django 5.2.15 on 2026-07-07 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0017_project_is_template_project_template_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. created, status_changed, item_added, item_removed', max_length=64, verbose_name='Action')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='parametric_bom.project', verbose_name='Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Project log',
                'verbose_name_plural': 'Project logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
