# Generated by Django 5.2.15 on 2026-07-07 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0018_projectlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Role name')),
                ('permissions', models.JSONField(blank=True, default=list, help_text='List of permission codenames', verbose_name='Permissions')),
                ('is_preset', models.BooleanField(default=False, help_text='Preset roles cannot be deleted', verbose_name='Is preset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='parametric_bom.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project role',
                'verbose_name_plural': 'Project roles',
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='parametric_bom.project', verbose_name='Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships_rbac', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='parametric_bom.projectrole', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Project membership',
                'verbose_name_plural': 'Project memberships',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
