# Generated by Django 5.2.15 on 2026-07-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0020_seed_project_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametricbomitem',
            name='name_formula',
            field=models.CharField(blank=True, default='', help_text='Formula for the display name of this BOM item. Example: CONCAT("支柱-", param.高度, "mm")', max_length=512, verbose_name='Name formula'),
        ),
    ]
