# Generated by Django 5.2.15 on 2026-07-21 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0021_parametricbomitem_name_formula'),
        ('parametric_bom', '0022_fix_name_formula_default'),
    ]

    operations = [
    ]
