# Generated by Django 5.2.15 on 2026-07-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0024_add_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='batch_name',
            field=models.CharField(blank=True, default=None, help_text='Group identifier for batch display', max_length=64, null=True, verbose_name='Batch name'),
        ),
    ]
