# Generated by Django 5.2.15 on 2026-07-21 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0026_projectitem_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Batch name')),
                ('status', models.CharField(choices=[('editing', '✏️ 编辑中'), ('locked', '🔒 已锁定'), ('completed', '✅ 已完成')], default='editing', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='parametric_bom.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project batch',
                'verbose_name_plural': 'Project batches',
                'unique_together': {('project', 'name')},
            },
        ),
    ]
