# Generated by Django 5.2.15 on 2026-07-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0027_projectbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partparameterconfig',
            name='computation_formula',
        ),
        migrations.RemoveField(
            model_name='partparameterconfig',
            name='is_computed',
        ),
    ]
