# Generated by Django 5.2.15 on 2026-07-22 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0028_remove_partparameterconfig_computation_formula_and_more'),
        ('part', '0150_part_maximum_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partparameterconfig',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the parameter was soft-deleted', null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='partparameterconfig',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-delete flag — parameter is hidden but not removed from DB', verbose_name='Deleted'),
        ),
        migrations.CreateModel(
            name='ParameterChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore')], max_length=16, verbose_name='Action')),
                ('param_name', models.CharField(blank=True, default='', help_text='Name of the parameter at the time of the action', max_length=128, verbose_name='Parameter name')),
                ('field_name', models.CharField(blank=True, default='', help_text='Which field was changed (for update actions)', max_length=64, verbose_name='Field name')),
                ('old_value', models.TextField(blank=True, default='', verbose_name='Old value')),
                ('new_value', models.TextField(blank=True, default='', verbose_name='New value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('param_config', models.ForeignKey(blank=True, help_text='The parameter config this log entry relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to='parametric_bom.partparameterconfig', verbose_name='Parameter config')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_logs', to='part.part', verbose_name='Part')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Parameter change log',
                'verbose_name_plural': 'Parameter change logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
