# Generated by Django 5.2.15 on 2026-07-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0029_partparameterconfig_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partvariable',
            name='var_type',
            field=models.CharField(choices=[('number', '数值型'), ('integer', '整数型'), ('string', '文本型'), ('boolean', '布尔型')], default='number', help_text='Determines how the formula result is interpreted', max_length=16, verbose_name='Variable type'),
        ),
    ]
