# Generated by Django 5.2.15 on 2026-07-23 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0030_add_var_type_to_partvariable'),
        ('part', '0150_part_maximum_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "v1.0", "v2.0 优化版"', max_length=64, verbose_name='Version name')),
                ('description', models.TextField(blank=True, default='', help_text='Optional notes about this version', verbose_name='Description')),
                ('snapshot_data', models.JSONField(default=dict, help_text='Full JSON of all parametric configs at save time', verbose_name='Snapshot data')),
                ('is_active', models.BooleanField(default=False, help_text='Whether this version is the currently loaded one', verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('part', models.ForeignKey(help_text='The part this snapshot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='parametric_snapshots', to='part.part', verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Parametric snapshot',
                'verbose_name_plural': 'Parametric snapshots',
                'ordering': ['-created_at'],
                'unique_together': {('part', 'name')},
            },
        ),
    ]
