# Generated by Django 5.2.15 on 2026-07-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0031_add_parametric_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbatch',
            name='make_buy',
            field=models.CharField(choices=[('采购', '采购'), ('自制', '自制'), ('外协', '外协')], default='采购', help_text='制购类别', max_length=32, verbose_name='Make/Buy category'),
        ),
        migrations.AddField(
            model_name='projectbatch',
            name='reason',
            field=models.CharField(blank=True, default='按合同下单', help_text='申请理由', max_length=256, verbose_name='Application reason'),
        ),
        migrations.AddField(
            model_name='projectbatch',
            name='storage_dest',
            field=models.CharField(choices=[('入仓库', '入仓库'), ('车间领用', '车间领用'), ('现场安装', '现场安装')], default='入仓库', help_text='入库去向', max_length=32, verbose_name='Storage destination'),
        ),
    ]
