# Generated by Django 5.2.15 on 2026-07-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0032_add_batch_meta_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbatch',
            name='storage_dest',
            field=models.CharField(choices=[('入仓库', '入仓库'), ('车间领用', '车间领用'), ('入仓库，车间领用', '入仓库，车间领用'), ('现场安装', '现场安装')], default='入仓库，车间领用', help_text='入库去向', max_length=64, verbose_name='Storage destination'),
        ),
    ]
