# Generated by Django 5.2.15 on 2026-07-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0033_update_storage_dest_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectbatch',
            name='make_buy',
            field=models.CharField(choices=[('采购', '采购'), ('自制', '自制'), ('外协', '外协'), ('利旧', '利旧')], default='采购', help_text='制购类别', max_length=32, verbose_name='Make/Buy category'),
        ),
    ]
