# Generated by Django 5.2.15 on 2026-07-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametric_bom', '0034_add_li_jiu_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='part_snapshot',
            field=models.JSONField(blank=True, help_text='Part parameters, attachments, and description cached at add-to-project time', null=True, verbose_name='Part snapshot'),
        ),
    ]
