#!/usr/bin/env python3
"""Fix the broken onchange escaping in configurator.html - exactly targeted."""
import os

path = '/root/inventree-source/InvenTree-master/src/backend/parametric_bom/templates/parametric_bom/configurator.html'

with open(path, 'rb') as f:
    data = f.read()

# The problem: the file has literal backslash-doublequote sequences
# like: onchange=\"onBomModeToggle(\" that break JavaScript
# These were generated by Python's \\" inside single-quoted strings

# Find all occurrences of the broken pattern
# Search for: onchange=\"onBomModeToggle(
search = b'onchange=\\"onBomModeToggle('
idx = data.find(search)
found = 0
while idx >= 0:
    found += 1
    # Get the full line
    line_start = data.rfind(b'\n', 0, idx) + 1
    line_end = data.find(b'\n', idx)
    line = data[line_start:line_end]
    
    print(f"Occurrence {found}:")
    print(f"  {line}")
    print()
    
    idx = data.find(search, idx + 1)

if found == 0:
    print("Pattern not found. Checking for other patterns...")
    # Maybe there are no backslashes?
    alt = b'onchange="onBomModeToggle('
    idx2 = data.find(alt)
    while idx2 >= 0:
        line_start = data.rfind(b'\n', 0, idx2) + 1
        line_end = data.find(b'\n', idx2)
        print(f"  Found without backslash: {data[line_start:line_end]}")
        idx2 = data.find(alt, idx2 + 1)
        if idx2 > 50000: break
