#!/usr/bin/env python3
"""Fix quote escaping in configurator.html - target specific patterns."""
import re

path = '/root/inventree-source/InvenTree-master/src/backend/parametric_bom/templates/parametric_bom/configurator.html'
with open(path, 'r') as f:
    content = f.read()

# The bug: the Python script wrote literal backslash-quote sequences
# like: onchange=\"onBomModeToggle(123\", 'qty_formula', this.checked)\">
# These should be: onchange="onBomModeToggle(123, 'qty_formula', this.checked)">

# Pattern to find: the onchange handler in loadBomFormulaConfigs string concat version
# Search for: onchange=\"onBomModeToggle( + number + \", ' + string + \"', this.checked)\">
old = ' onchange=\\\"onBomModeToggle('
# After variable: \", '\"

# Strategy: find the unique marker and replace around it
# The marker is: onchange=\"onBomModeToggle(
# which should be: onchange="onBomModeToggle(

# Replace backslash-quote with just quote inside JavaScript single-quoted strings
# The problematic pattern is: \" inside JavaScript '...' strings
# that were generated by Python's \\" inside single-quoted Python strings

# Specific replacements:
# 1. onchange=\"onBomModeToggle(  →  onchange="onBomModeToggle(
# 2. item.pk + \", '  →  item.pk + ", '
# 3. m.key + \"', this.checked)\">\"  →  m.key + "', this.checked)"> 
# Wait, m.key + "', this.checked)"> is wrong too - needs the outer string properly

# Let me look at the actual file content around the problematic area
idx = content.find('onchange')
while idx >= 0:
    # Check if this onchange is in the loadBomFormulaConfigs section (after line ~4916)
    line_start = content.rfind('\n', 0, idx) + 1
    line_num = content[:line_start].count('\n') + 1
    
    if line_num >= 4916:
        # Get the surrounding text
        start = idx
        end = min(idx + 120, len(content))
        snippet = content[start:end]
        
        # Check if it has the backslash-doublequote pattern
        if '\\"' in snippet:
            print(f'Found issue at line ~{line_num}')
            print(repr(snippet))
            
            # Fix: Replace \" sequences that are inside JS single-quoted strings
            # The pattern is: onchange=\"onBomModeToggle(123\", 'qty_formula', this.checked)\">
            # Should be: onchange="onBomModeToggle(123, 'qty_formula', this.checked)">
            
            # Strategy: replace the whole onchange attribute
            # Find the end of this HTML tag attribute
            attr_start = content.rfind('onchange', 0, end)
            attr_end = content.find('>', attr_start)
            if attr_end > attr_start:
                # Find where the previous attribute ends
                prev_attr_end = content.rfind('"', idx - 100, idx)
                if prev_attr_end > content.rfind('>', idx - 200, idx):
                    full_attr = content[prev_attr_end:attr_end+1]
                    print(f'Full attr: {repr(full_attr)}')
        
    idx = content.find('onchange', idx + 1)
    if idx > len(content):
        break

print('Done scanning')
